services:
  staticfilesnew:
    image: nginx:alpine
    container_name: staticfilesnew
    environment:
      - NGINX_PORT=80
    ports:
      - 8081:80
    volumes:
      - ${DOCKER_STORAGE}/staticfiles:/usr/share/nginx/html
      - ./mime.types:/etc/nginx/mime.types
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
