version: "3.8"

services:
  staticfiles:
    image: halverneus/static-file-server:latest
    container_name: staticfiles
    environment:
      - "FOLDER=/staticfiles"
      - "DEBUG=true"
    ports:
      - 8088:8080
    volumes:
      - ${DOCKER_STORAGE}/staticfiles:/staticfiles
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
