version: "3.8"

services:
  traefik:
    labels:
      # This sets up an http -> https redirect for all endpoints.
      - traefik.enable=true
      - traefik.http.routers.https-only.rule=HostRegexp(`{host:.*}`)
      - traefik.http.routers.https-only.priority=99
      - traefik.http.routers.https-only.entrypoints=http
      - traefik.http.routers.https-only.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.subdomain=traefik
      - traefik.http.routers.traefik.rule=Host(`traefik.${BASE_DOMAIN}`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
